routes/web.php
	     ->name('unit_deposit_requests.index')
	     ->middleware('permission:view-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}", "UnitDepositRequestController@show")
	     ->name('unit_deposit_requests.show')
	     ->middleware('permission:view-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}/updateReceivingAmount", "UnitDepositRequestController@showUpdateReceivingAmountForm")
	     ->name('unit_deposit_requests.update.receving_amount')
	     ->middleware('permission:view-unit-deposit-request');
	Route::post("/unit_deposit_requests/{id}/updateReceivingAmount", "UnitDepositRequestController@UpdateReceivingAmount")
		 ->middleware('permission:update-unit-deposit-request');
	Route::post('/unit_deposit_requests/{id}/cancel', 'UnitDepositRequestController@cancel')
		 ->name('unit_deposit_requests.cancel')
		 ->middleware('permission:cancel-unit-deposit-request');
	Route::post('/unit_deposit_requests/{id}/void', 'UnitDepositRequestController@void')
		 ->name('unit_deposit_requests.void')
		 ->middleware('permission:void-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}/getPayment", "UnitDepositRequestController@getPayment")->name('unit_deposit_requests.payment');

	// Unit Hold Request
	Route::get('/unit_hold_requests', 'UnitHoldRequestController@index')
		 ->name('unit_hold_requests.index')
	     ->middleware('permission:view-unit-hold-request');
	Route::get("/unit_hold_requests/{id}", "UnitHoldRequestController@show")
	     ->name('unit_hold_requests.show')
	     ->middleware('permission:view-unit-hold-request');

	// Contract Route
	Route::get('/contracts', "ContractController@index")
		 ->name('contracts.index')
		 ->middleware('permission:view-contract');

	Route::get('/contracts/export', 'ContractController@export')
		 ->name('contracts.export')
		 ->middleware('permission:view-contract');

	Route::get('/contracts/create', "CreateContractController@showCreateForm")
		 ->name('contracts.create')
		 ->middleware('permission:create-contract');

	Route::get('/contracts/{id}/edit', "EditContractController@showEditForm")
		 ->name('contracts.edit')
		 ->middleware('permission:update-contract');

    Route::get('/contracts/{id}/print', 'ContractPdfController@getContractPdfFile')
		 ->name('contracts.print')
		 ->middleware('permission:view-contract');

    Route::get('/contracts/{id}/upload', 'UploadContractController@showContractUploadForm')
		 ->name('contracts.upload')
		 ->middleware('permission:update-contract');
    Route::post('/contracts/{id}/upload', 'UploadContractController@uploadContractPDF')
    	 ->middleware('permission:update-contract');;

	Route::post('/contracts/create', "CreateContractController@store")
	     ->middleware('permission:create-contract');

	Route::post('/contracts/{id}/cancel', "CancelContractController@processCancellationRequest")
	     ->middleware('permission:cancel-contract');
	Route::post('/contracts/{id}/void', "VoidContractController@processVoidRequest")
	     ->middleware('permission:void-contract');

	Route::put('/contracts/{id}', "EditContractController@update")
		 ->name('contracts.update')
		 ->middleware('permission:update-contract');
	// End Contract Route

	// Contract Attachment Route
    Route::delete('/contract_attachments/{id}', "ContractAttachmentController@delete")
         ->name('contract_attachments.destroy');
	// Contract Attachment Route

	// Loan Route
	Route::post('/loan/amortization-schedule', "LoanController@getAmortizationSchedule")
		 ->name('loan.amortization-schedule');
    Route::get('/loan/payment_date', "LoanController@paymentDate");
	// End Loan

	// Banner
    Route::resource('banners', 'BannerController');
	// End Banner

	// Bank
    Route::resource('banks', 'BankController');
	// End Bank

	// Banner
    Route::resource('categories', 'CategoryController');   
	// End Banner

   	// Banner
    Route::resource('posts', 'PostController');    
	// End Banner

	Route::resource('projects', 'ProjectController');
	Route::get('projects/{id}/delete', "ProjectController@showDeleteForm")->name('projects.delete');
	Route::get('projects/{id}/restore', "ProjectController@showRestoreForm")->name('projects.restore');
	Route::post('projects/{id}/restore', "ProjectController@restore");
	Route::delete('projects/{id}/media', 'ProjectController@deleteMedia')->middleware('permission:update-project');

	Route::resource('companies', 'CompanyController');
	Route::get('companies/{id}/delete', 'CompanyController@delete')->name('companies.delete');

	Route::resource('payment_options', 'PaymentOptionController');
	Route::get('payment_options/{id}/delete', "PaymentOptionController@showDeleteForm")->name('payment_options.delete');
	Route::get('payment_options/{id}/restore', "PaymentOptionController@showRestoreForm")->name('payment_options.restore');
	Route::post('payment_options/{id}/restore', "PaymentOptionController@restore");
	Route::get('payment_options/{id}', "PaymentOptionController@show");

	// Discount Promtion Route
	Route::resource('discount_promotions', 'DiscountPromotionController');
	Route::post('discount_promotions/{id}/discount_promotion_items', 'DiscountPromotionController@addItem');
	Route::delete('discount_promotions/{id}/discount_promotion_items/{item_id}', 'DiscountPromotionController@removeItem');

	Route::resource('unit_types', 'UnitTypeController');
	Route::get('unit_types/{id}/delete', "UnitTypeController@showDeleteForm")->name('unit_types.delete');
	Route::get('unit_types/{id}/restore', "UnitTypeController@showRestoreForm")->name('unit_types.restore');
	Route::post('unit_types/{id}/restore', "UnitTypeController@restore");	
	Route::get('unit_types/{id}/saleable', "UnitTypeController@showSetSaleableStatusForm")->name('unit_types.set_saleable_status');
	Route::post('unit_types/{id}/saleable', "UnitTypeController@SetSaleableStatus");	
	Route::get('unit_types/{id}/payment_option', "UnitTypeController@getPaymentOption");
	Route::get('unit_types/{id}/clone_payment_option',"UnitTypeController@getClonePaymentOptionForm")->name("unit_types.clone");
	Route::post('unit_types/{id}/clone_payment_option',"UnitTypeController@clone");
	Route::post('unit_types/{id}/addMedia', 'UnitTypeController@addMedia')->name('unit_types.add_media');
	Route::delete('unit_types/{id}/deleteMedia', 'UnitTypeController@deleteMedia')->name('unit_types.delete_media');

	// Unit Route
	Route::get('/units', "UnitController@index")
		 ->name("units.index")->middleware('permission:view-unit');
	Route::get('/units/new', "UnitController@create")
		 ->name("units.create")->middleware('permission:create-unit');
	Route::get('/units/import', "UnitController@showImportForm")
		 ->name("units.import")->middleware('permission:import-unit');
    Route::post('/units/import', "UnitController@import")->middleware('permission:import-unit');
    Route::get('/units/bulkStatusModify', 'UnitStatusModifyController@showForm')
	     ->name('units.bulk_status_modify')->middleware('permission:modify-status-unit');
	Route::post('/units/bulkStatusModify', 'UnitStatusModifyController@modifyStatus')
		 ->middleware('permission:modify-status-unit');
    Route::get('/units/import_template', "UnitController@getImportTempalte")
    	 ->name("units.import_template")->middleware('permission:import-unit');
	Route::get('/units/export', "UnitController@showExportForm")
	 	 ->name("units.export")->middleware('permission:export-unit');
	Route::get('/units/saleReport', "UnitController@exportSaleReport")
	 	 ->name("units.report.sale")->middleware('permission:export-unit');

	Route::post('/units/export', "UnitController@export")->middleware('permission:export-unit');
    Route::get('/units/{id}/edit', "UnitController@edit")    
		 ->name("units.edit")->middleware('permission:update-unit');		
	Route::get('/units/{id}', "UnitController@show")
		 ->name("units.show")->middleware('permission:view-unit');
	Route::get('/units/{id}/actions', "UnitController@getActions")
		 ->name("units.get.actions")->middleware('permission:view-unit');
	Route::get('/units/{id}/activities', "UnitController@getActivities")
		 ->name("units.get.activities")->middleware('permission:view-unit');
	Route::get('/units/{id}/change_status', "UnitController@showChangeStatusForm")
		 ->name("units.status.change");
	Route::post('/units/{id}/change_status', "UnitController@changeStatus");	
    Route::post('/units', "UnitController@store")
         ->name('units.store')->middleware('permission:create-unit');
    Route::put('/units/{id}', "UnitController@update")
         ->name('units.update')
         ->middleware('permission:update-unit'); 
    Route::post('/units/{id}/updateSaleable', "UnitController@updateSaleableStatus")
         ->name("units.saleable")->middleware('permission:update-unit');
    Route::post('/units/{id}/updateActive', "UnitController@updateActiveStatus")
    	 ->name("units.saleable")->middleware('permission:update-unit');
	// End Unit Route
	
	// User member
	Route::get('/user/{id}/members', "UserController@getMembers")
		 ->name("user.get.members");
	// End User member

	// Unit Action Route
    Route::get('/unit_actions', "UnitActionController@index")
    	 ->name('unit_actions.index');
	// End Unit Action Route

   	// Sale Representative
   	Route::resource('sale_representatives', 'SaleRepresentativeController');
   	Route::get('sale_representatives/{id}/delete', "SaleRepresentativeController@showDeleteForm")->name('sale_representatives.delete');
    // End Sale Representative

   	// Mobile App Version
   	Route::resource('app_versions', 'AppVersionController');
   	// End Mobile App Version

   	// Miscellanous Route          	
	Route::get('/notifications', "NotificationController@showNotification")
		 ->name('notification.show');
	Route::get('/notifications/readAll', "NotificationController@markAllAsRead")
		 ->name('notification.mark.read.all');
	Route::post('/notifications/{id}/markAsRead', "NotificationController@markAsRead")
		 ->name('notification.mark.read');

app/PaymentOption.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Builder;

class PaymentOption extends Model
{
    use SoftDeletes;


    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('sortByName', function (Builder $builder) {
            $builder->orderBy('unit_type_id', 'asc');
            $builder->orderBy('name', 'asc');
        });
    }

	/**
     * The attributes that need to be cast to Carbon DateTime Object
     *
     * @var array
    */
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
    */
    protected $fillable = [ 
        'user_id', 
        'unit_type_id', 
        'name',
        'deposit_amount',
        'loan_duration', 
        'interest', 
        'special_discount',
        'is_first_payment',
        'is_first_payment',
        'first_payment_duration',
        'first_payment_percentage'
    ];

    protected $casts = [
        'is_first_payment' => 'boolean',
        
    ];

    // Model Relationship go here
    public function createdBy() {
        return $this->belongsTo('App\User', 'user_id', "id")->select(['id', 'name', 'avatar', 'phone_number']);
    }

    public function unitType() {
        return $this->belongsTo('App\UnitType')->select(['id','project_id','name','short_code']);
    }
    // End Model Relationshipa   

    // Query Scope
    public function scopeOfStatus($query, $status = '' ) 
    {
        switch ($status) {
            case 'all':
                return $query->withTrashed();                
                break;
            case 'removed': 
                return $query->onlyTrashed();                     
                break;
            case 'active':
                return $query;
            default:   
                return $query->withTrashed();
                break;
        }     
    }
    // End Query Scope
}   

app/Http/Controllers/Api/PaymentOptionController.php
<?php

namespace App\Http\Controllers\Api;

use Validator;
use App\PaymentOption;
use App\UnitType;
use App\Http\Resources\PaymentOption as PaymentOptionResource;
use App\Http\Resources\PaymentOptionCollection;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PaymentOptionController extends Controller
{
    protected $validationRules =  [
	    'unit_type_id'		=> 'required|integer|exists:unit_types,id', 
        'name' 				=> 'required|string|max:255', 
        'loan_duration' 	=> 'required|integer|min:0|max:255',
        'interest'			=> 'required|integer|min:0|max:100',
        'special_discount' 	=> 'integer|min:0|max:100'
	];

	public function all(Request $request)
	{
		if ( $request->input("embed") ) {			
			$relationships = explode(',', trim($request->input('embed')) );
			return new PaymentOptionCollection( PaymentOption::with($relationships)->get() );
		}
		return new PaymentOptionCollection( PaymentOption::all() );
	}

	public function create(Request $request) 
	{	
		$validator = Validator::make( $request->all(), $this->getValidationRules() );

		if ($validator->fails()) {
            return $this->sendErrorJsonResponse($validator->errors()->first(), 422);
        }

        $data = $request->all();
        $data['user_id'] = $request->user()->id;

        try {
        	$payment_option = PaymentOption::create($data);	
        } catch (Exception $e) {
        	$this->sendErrorJsonResponse(__('Internal Server Error!'), 500);
        }
        return new PaymentOptionResource( $payment_option );
	}

	public function get(Request $request, $id)
	{
		$payment_option = PaymentOption::where('id', $id)->firstOrFail();

		if ( $request->input("embed") ) {			
			$relationships = explode(',', trim($request->input('embed')) );
			$payment_option->load($relationships);
		}
		return new PaymentOptionResource( $payment_option );
	}

	public function update(Request $request, $id)
	{
		$payment_option = PaymentOption::where('id', $id)->firstOrFail();

		$validator = Validator::make( $request->all(), $this->getValidationRules() );

		if ($validator->fails()) {
            return $this->sendErrorJsonResponse($validator->errors()->first(), 422);
        }

        $data = $request->all();
        $data['user_id'] = $request->user()->id;

        try {
        	$payment_option->fill($data);	
        	if ( ! $payment_option->save() ){
	            $this->sendErrorJsonResponse( __('There are some problems while trying to updating your request'), 500);			
			}

        } catch (Exception $e) {
        	$this->sendErrorJsonResponse(__('Internal Server Error!'), 500);
        }
        return new PaymentOptionResource( $payment_option );
	}

	public function remove(Request $request, $id)
	{
		$payment_option = PaymentOption::where('id', $id)->firstOrFail();
		try {
			$payment_option->user_id = $request->user()->id;
			$payment_option->deleted_at = \Carbon\Carbon::now();
			$payment_option->save();
			return $this->sendSuccessResponse( __("Delete Successful.") , 200);
		} catch (Exception $e) {
			return $this->sendErrorJsonResponse(__('Internal Server Error!'), 500);
		}
	}

	public function getByUnitTypeId(Request $request, $unit_type_id)
	{
		$unit_type = UnitType::findOrFail($unit_type_id);

		if ( $request->input("embed") ) {			
			$relationships = explode(',', trim($request->input('embed')) );
			return new PaymentOptionCollection( PaymentOption::where('unit_type_id', $unit_type_id)->with($relationships)->get() );
		}
		return new PaymentOptionCollection( PaymentOption::where('unit_type_id', $unit_type_id)->get() );
	}

	public function getValidationRules(){
	  	return $this->validationRules;
	}

	public static function validatedPaymentOptionFromRequest(Array $data) {
		$default_payment_option = [
			"payment_option_id" => null,
			"loan_duration" => 0,
			"interest" => 0,
			"special_discount" => 0,
			"is_first_payment" => 0,
			"first_payment_duration" => 0,
			"first_payment_percentage" => 0,
			"first_payment_amount" => 0,
		];
		if ( array_key_exists("payment_option_id", $data) ) {			
			$data['loan_duration'] = 0;
			$data['interest'] = 0;
			$data['special_discount'] = 0;
			$data['is_first_payment'] = 0;
			$data['first_payment_duration'] = 0;
			$data['first_payment_percentage'] = 0;
			$data['first_payment_amount'] = 0;
		} else {
			$data['payment_option_id'] = null;
			$data['loan_duration'] = $data['loan_duration'] ?? 0;
			$data['interest'] =  $data['interest'] ?? 0;
			$data['special_discount'] = $data['special_discount'] ?? 0;
			$data['is_first_payment'] = $data['is_first_payment'] ?? 0;
			$data['first_payment_duration'] = $data['first_payment_duration'] ?? 0;
			$data['first_payment_percentage'] =  $data['first_payment_percentage'] ?? 0;
			$data['first_payment_amount'] = $data['first_payment_amount'] ?? 0;
		}
		return $data;
	}
}

resources/views/admin/payment_option/action.blade.php
<ul class="action-list">
	@if($payment_option->trashed())
		<li><a href="{{ route('admin.payment_options.restore',['id'=>$payment_option->id]) }}" class="text-success">Restore</a></li>
	@else
		<li><a href="{{ route('admin.payment_options.edit',['id'=>$payment_option->id]) }}" class="text-success">Edit</a></li>
		<li><a href="{{ route('admin.payment_options.delete',['id'=>$payment_option->id]) }}" class="text-danger">Remove</a></li>
	@endif
</ul>

resources/views/admin/payment_option/delete.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('content')
<div class="container">
    <form method="POST" action="{{ route('admin.payment_options.destroy', [ 'id' => $payment_option->id ]) }}" novalidate="novalidate" autocomplete="false">
    @csrf        
    {{ method_field("DELETE") }}
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __("Delete") }} {{__("Project")}} : <strong>{{ $payment_option->name }}</strong></div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <input type="hidden" name="id" value="{{ $payment_option->id }}" readonly="readonly">
                        <p class="mb-0">Are you sure want to delete the payment option : <strong>{{ $payment_option->name }}</strong>?</p>
                        <p class="text-muted"><small>Resource will not be permanently deleted from database. But, it just won't be visible to the user.</small></p>
                    </div>
                    
                    <div class="card-footer">
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger">{{ __("Yes, Delete it.") }}</button>
                            </div>
                            <div class="col">
                                <a href="{{ route('admin.payment_options.index') }}" class="btn btn-secondary float-right">{{ __("No, Back to Payment Option list.") }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/admin/payment_option/index.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('content')
<div class="container" id="main-container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <form method="GET" action="{{ route('admin.payment_options.index') }}" name="user-search-from" novalidate="novalidate" autocomplete="false">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                           {{ __("Payment Option List") }} : <a href="{{route('admin.payment_options.create')}}" class="btn btn-primary btn-sm ">{{ __("Create New") }} {{ __("Payment Option") }}</a>
                        </div>
                        <div class="col-sm-12 col-md-auto" style="width:400px;">                           
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Name..." aria-label="Name, email or phone number" aria-describedby="button-search" name="term" value="{{ Request::query('term') ? Request::query('term') : '' }}">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="submit" id="search-button">Search</button>
                                    <a class="btn btn-outline-secondary" data-toggle="collapse" href="#sub-header-collapse">More Filter</a>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
                <div class="card-sub-header card-bg-grey collapse {{ array_except(Request::query(),'page') ? 'show' : '' }}" id="sub-header-collapse">
                    <div class="sub-header-box-wrapper">
                        <div class="form-row">
                            <div class="input-group input-group-sm col-md-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="unit_type">Unit Type</label>
                                </div>
                                <select class="form-control" name="unit_type" id="unit_type">
                                    <option value="">Choose...</option>
                                @foreach ( $projects as $project )
                                    <optgroup label="{{ $project->name }}">
                                    @foreach( $project->unitTypes as $unit_type )
                                        <option value="{{ $unit_type->id }}" 
                                                {{ $unit_type->id == Request::query('unit_type') ? "selected" : "" }} >
                                                {{ $unit_type->name }}
                                        </option>
                                    @endforeach
                                    </optgroup>
                                @endforeach
                                </select> 
                            </div>
                            <div class="input-group input-group-sm col-md-2">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="status">Status</label>
                                </div>                                  
                                <select class="form-control" name="status" id="status">
                                    <option value="all" {{ Request::query('status') == 'all' ? 'selected' : '' }}>All</option>
                                    <option value="active" {{ Request::query('status') == 'active' ? 'selected' : '' }}>Active</option>
                                    <option value="removed" {{ Request::query('status') == 'removed' ? 'selected' : '' }}>Removed</option>
                                </select>
                            </div>
                            <button class="btn btn-sm btn-primary" type="submit" id="fileter-button">Show</button>    
                            <a href="{{ route('admin.user.all') }}" class="btn btn-secondary btn-sm ml-md-2">Clear Filter</a>
                        </div>
                    </div>
                </div>
                <div class="card-body p-0">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif
                    <table class="table table-hover table-action mb-0">
                        <thead>
                            <tr>                                
                                <th scope="col">Name</th>
                                <th scope="col" width="200px">Unit Type (Project)</th>
                                <th scope="col" width="170px">Loan Option</th>
                                <th scope="col" width="130px">Created By</th>
                                <th scope="col" width="170px">Timestamp</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($payment_options as $payment_option)
                            <tr class="{{ $payment_option->trashed() ? 'table-secondary' : '' }}">
                                <td scope="row" class="action-td">
                                    <a href="{{ route('admin.payment_options.edit',['id'=>$payment_option->id]) }}" class="title">{{ $payment_option->name }}</a>
                                    @include('admin.payment_option.action')
                                </td>
                                <td>
                                    <strong>{{ isset($payment_option->unitType) ? $payment_option->unitType->name : "N/A" }} ({{ isset($payment_option->unitType) ? $payment_option->unitType->project->name : "N/A" }})</strong>
                                </td>
                               
                                <td>
                                    <p class="mb-0">Initail Deposit: <strong>{{ number_format($payment_option->deposit_amount,2) }}</strong></p>
                                    <p class="mb-0">Duration: <strong>{{ $payment_option->loan_duration }}</strong></p>
                                    <p class="mb-0">Interest: <strong>{{ $payment_option->interest }} %</strong></p>
                                    <p class="mb-0">Special Discount: <strong>{{ $payment_option->special_discount }}%</strong></p>

                                </td>
                                <td>{{ $payment_option->createdBy->name }}</td>
                                <td>
                                    @if( $payment_option->trashed() )
                                    <ul class="mb-0 text-couple">                                       
                                        <li>
                                            <p>
                                                <small>Created At:</small>
                                                <span class="title">{{ $payment_option->created_at }}</span>
                                            </p>                                            
                                        </li>
                                        <li>
                                            <p>
                                                <small>Deleted At:</small>
                                                <span class="title">{{ $payment_option->deleted_at }}</span>
                                            </p>
                                        </li>
                                    </ul>
                                    @else
                                    <ul class="mb-0 text-couple">                                       
                                        <li>
                                            <p>
                                                <small>Created At:</small>
                                                <span class="title">{{ $payment_option->created_at }}</span>
                                            </p>                                            
                                        </li>
                                        <li>
                                            <p>
                                                <small>Updated At:</small>
                                                <span class="title">{{ $payment_option->updated_at }}</span>
                                            </p>
                                        </li>
                                    </ul>
                                    @endif
                                </td>


                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            </form>
            {{ $payment_options->appends(request()->except(['page','_token'])) }}
        </div>
    </div>
</div>
@endsection

@push("scripts")
<script type="text/javascript">
    $(document).ready(function (){
        $('.select2').select2({ theme:"bootstrap4" });
    });
</script>
@endpush

resources/views/admin/payment_option/restore.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('content')
<div class="container">
    <form method="POST" action="{{ route('admin.payment_options.restore', [ 'id' => $payment_option->id ]) }}" novalidate="novalidate" autocomplete="false">
    @csrf          
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __("Restore") }} {{__("Payment Option")}} : <strong>{{ $payment_option->name }}</strong></div>
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <input type="hidden" name="id" value="{{ $payment_option->id }}" readonly="readonly">
                        <p class="mb-0">Are you sure want to recover the payment option : <strong>{{ $payment_option->name }}</strong>?</p>
                        <p class="text-muted"><small>Recovered resource will be available for user.</small></p>
                    </div>
                    
                    <div class="card-footer">
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-primary">{{ __("Yes, restore it.") }}</button>
                            </div>
                            <div class="col">
                                <a href="{{ route('admin.payment_options.index') }}" class="btn btn-secondary float-right">{{ __("No, Back to Payment Option list.") }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@endsection