routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/', '/login', 301);
// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', "Auth\LoginController@authenticate");
Route::post('/logout', "Auth\LoginController@logout")->middleware(['auth'])->name('logout');
Route::get("/change-password", "Auth\ChangePasswordController@showChangePasswordForm")->middleware(['auth'])->name('password.change');
Route::post("/change-password", "Auth\ChangePasswordController@changePassword")->middleware(['auth']);

// Contract Template Route
Route::get("/contract_template/{template_path}/preview", "ContractTemplatePreviewController@preview")
     ->name('admin.contract_templates.preview');
Route::get("/ios/install", "AppDownloadController@showIOSDownloadView")->name("app_download.ios");
Route::get("/ios/install/dev", "AppDownloadController@showIOSDevDownloadView")->name("app_download.ios_dev");
Route::get('/contract/templates', 'ContractTemplatePreviewController@showTemplate')
    	 ->name('contracts.template')
    	 ->middleware(['role:contract_controller']);
// End Contract Template Route

Route::namespace("Admin")->prefix('admin')->name("admin.")->middleware(['auth'])->group( function () {
	Route::get('/users', "UserController@index")->name('user.all')
		 ->middleware('permission:view-user');
	Route::get('/users/new', "UserController@create")->name('user.new')
	     ->middleware('permission:create-user');
	Route::get('/users/get_agents', "UserController@getAgents")->name('user.role.agent');
	Route::get('/users/{id}', 'UserController@show')->name('user.show');
	Route::get('/users/{id}/tokens', "UserTokenController@show")->name('user.token.show')
		 ->middleware('permission:view-user');
	Route::get('/users/{id}/edit', "UserController@edit")->name('user.edit')
		 ->middleware('permission:update-user');
	Route::get('/users/{id}/password/reset', "UserController@showPasswordForm")->name('user.password.show')
		 ->middleware('permission:update-user');
	Route::post('/users/{id}/password/reset', "UserController@resetPassword")->name('user.password.reset')
		 ->middleware('permission:update-user');
	Route::post('/users', "UserController@store")->name('user.create')
		 ->middleware('permission:create-user');
	Route::put('/users/{id}', "UserController@update")->name('user.update')
		 ->middleware('permission:update-user');

	Route::delete('/tokens/{id}', "UserTokenController@destroy")->name('user.token.delete')
		 ->middleware('permission:update-user');

	Route::middleware('role:administrator')->group( function () {
		Route::get('/roles', "RoleController@index")->name('role.all');
		Route::get('/roles/new', "RoleController@create")->name('role.new');
		Route::get('/roles/{id}/edit', "RoleController@edit")->name('role.edit');
		Route::get('/roles/{id}/remove', "RoleController@remove")->name('role.remove');	
		Route::post('/roles', "RoleController@store")->name('role.create');
		Route::put('/roles/{id}', "RoleController@update")->name('role.update');
		Route::delete('/roles/{id}', "RoleController@delete")->name('role.delete');
	});

	Route::get('/contract_requests', "ContractRequestController@index")
		 ->name('contract_request.all');	
	Route::get('/contract_requests/{id}', "ContractRequestController@show")
		 ->name('contract_request.show');
	Route::put('/contract_requests/{id}', "ContractRequestController@update")
	     ->name('contract_request.update');   
	Route::get('/contract_requests/{id}/view_payment_sample', 'ContractRequestController@showMortgage')
		 ->name('contract_request.view_payment_sample');

	// Unit Contract Request
	Route::get("/unit_contract_requests", "UnitContractRequestController@index")
	     ->name('unit_contract_requests.index');	
	Route::get("/unit_contract_requests/{id}", "UnitContractRequestController@show")
	     ->name('unit_contract_requests.show');
	Route::get("/unit_contract_requests/{id}/createContract", "UnitContractRequestController@showCreateContractForm")
	     ->name('unit_contract_requests.create_contract')
	      ->middleware('permission:create-contract');;
	Route::get('/unit_contract_requests/{id}/print', "UnitContractRequestController@printRequest")
		 ->name('unit_contract_requests.print');

	// Unit Deposit Request
	Route::get("/unit_deposit_requests", "UnitDepositRequestController@index")
	     ->name('unit_deposit_requests.index')
	     ->middleware('permission:view-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}", "UnitDepositRequestController@show")
	     ->name('unit_deposit_requests.show')
	     ->middleware('permission:view-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}/updateReceivingAmount", "UnitDepositRequestController@showUpdateReceivingAmountForm")
	     ->name('unit_deposit_requests.update.receving_amount')
	     ->middleware('permission:view-unit-deposit-request');
	Route::post("/unit_deposit_requests/{id}/updateReceivingAmount", "UnitDepositRequestController@UpdateReceivingAmount")
		 ->middleware('permission:update-unit-deposit-request');
	Route::post('/unit_deposit_requests/{id}/cancel', 'UnitDepositRequestController@cancel')
		 ->name('unit_deposit_requests.cancel')
		 ->middleware('permission:cancel-unit-deposit-request');
	Route::post('/unit_deposit_requests/{id}/void', 'UnitDepositRequestController@void')
		 ->name('unit_deposit_requests.void')
		 ->middleware('permission:void-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}/getPayment", "UnitDepositRequestController@getPayment")->name('unit_deposit_requests.payment');

	// Unit Hold Request
	Route::get('/unit_hold_requests', 'UnitHoldRequestController@index')
		 ->name('unit_hold_requests.index')
	     ->middleware('permission:view-unit-hold-request');
	Route::get("/unit_hold_requests/{id}", "UnitHoldRequestController@show")
	     ->name('unit_hold_requests.show')
	     ->middleware('permission:view-unit-hold-request');

	// Contract Route
	Route::get('/contracts', "ContractController@index")
		 ->name('contracts.index')
		 ->middleware('permission:view-contract');

	Route::get('/contracts/export', 'ContractController@export')
		 ->name('contracts.export')
		 ->middleware('permission:view-contract');

	Route::get('/contracts/create', "CreateContractController@showCreateForm")
		 ->name('contracts.create')
		 ->middleware('permission:create-contract');

	Route::get('/contracts/{id}/edit', "EditContractController@showEditForm")
		 ->name('contracts.edit')
		 ->middleware('permission:update-contract');

    Route::get('/contracts/{id}/print', 'ContractPdfController@getContractPdfFile')
		 ->name('contracts.print')
		 ->middleware('permission:view-contract');

    Route::get('/contracts/{id}/upload', 'UploadContractController@showContractUploadForm')
		 ->name('contracts.upload')
		 ->middleware('permission:update-contract');
    Route::post('/contracts/{id}/upload', 'UploadContractController@uploadContractPDF')
    	 ->middleware('permission:update-contract');;

	Route::post('/contracts/create', "CreateContractController@store")
	     ->middleware('permission:create-contract');

	Route::post('/contracts/{id}/cancel', "CancelContractController@processCancellationRequest")
	     ->middleware('permission:cancel-contract');
	Route::post('/contracts/{id}/void', "VoidContractController@processVoidRequest")
	     ->middleware('permission:void-contract');

	Route::put('/contracts/{id}', "EditContractController@update")
		 ->name('contracts.update')
		 ->middleware('permission:update-contract');
	// End Contract Route

	// Contract Attachment Route
    Route::delete('/contract_attachments/{id}', "ContractAttachmentController@delete")
         ->name('contract_attachments.destroy');
	// Contract Attachment Route

	// Loan Route
	Route::post('/loan/amortization-schedule', "LoanController@getAmortizationSchedule")
		 ->name('loan.amortization-schedule');
    Route::get('/loan/payment_date', "LoanController@paymentDate");
	// End Loan

	// Banner
    Route::resource('banners', 'BannerController');
	// End Banner

	// Bank
    Route::resource('banks', 'BankController');
	// End Bank

	// Banner
    Route::resource('categories', 'CategoryController');   
	// End Banner

   	// Banner
    Route::resource('posts', 'PostController');    
	// End Banner

	Route::resource('projects', 'ProjectController');
	Route::get('projects/{id}/delete', "ProjectController@showDeleteForm")->name('projects.delete');
	Route::get('projects/{id}/restore', "ProjectController@showRestoreForm")->name('projects.restore');
	Route::post('projects/{id}/restore', "ProjectController@restore");
	Route::delete('projects/{id}/media', 'ProjectController@deleteMedia')->middleware('permission:update-project');

	Route::resource('companies', 'CompanyController');
	Route::get('companies/{id}/delete', 'CompanyController@delete')->name('companies.delete');

	Route::resource('payment_options', 'PaymentOptionController');
	Route::get('payment_options/{id}/delete', "PaymentOptionController@showDeleteForm")->name('payment_options.delete');
	Route::get('payment_options/{id}/restore', "PaymentOptionController@showRestoreForm")->name('payment_options.restore');
	Route::post('payment_options/{id}/restore', "PaymentOptionController@restore");
	Route::get('payment_options/{id}', "PaymentOptionController@show");

	// Discount Promtion Route
	Route::resource('discount_promotions', 'DiscountPromotionController');
	Route::post('discount_promotions/{id}/discount_promotion_items', 'DiscountPromotionController@addItem');

app/Company.php
<?php

namespace App;

use App\Helpers\KhmerMonth;
use App\Helpers\NumberFormat;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
   	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'name_km',
        'address_line1',
        'address_line2',
        'name_en',
        'address_line1_en',
        'address_line2_en',
        'name_zh',
        'address_line1_zh',
        'address_line2_zh',
        'contact_phone_number',
        'email_address',
        'website',
        'tax_no',
        'tax_issued_date',
        'commercial_license_no',
        'commercial_license_issued_date',
        'nav_company_code'
    ]; 

    protected $dates = [
        'created_at',
        'updated_at',
        'tax_issued_date',
        'commercial_license_issued_date'
    ];

    // Model Relationship go here
    public function createdBy()
    {
    	 return $this->belongsTo('App\User', 'user_id', "id")->select(\App\User::getCreatedByFields());
    }

    public function projects()
    {
    	return $this->hasMany('App\Project');
    }
    // End Model Relationship

    // << km language helper
    public function getCommercialLicenseNoKmAttribute() 
    {
        return NumberFormat::convertToKhmerNumber($this->commercial_license_no);
    }

    public function getCommercialLicenseIssuedDayKmAttribute()
    {
        return NumberFormat::convertToKhmerNumber($this->commercial_license_issued_date->day);
    }

    public function getCommercialLicenseIssuedMonthKmAttribute()
    {
        return KhmerMonth::convertToKhmerMonth($this->commercial_license_issued_date->month);
    }

    public function getCommercialLicenseIssuedYearKmAttribute()
    {
        return NumberFormat::convertToKhmerNumber($this->commercial_license_issued_date->year);
    }
    // >>
}

resources/views/admin/contract/template/v2/km/template.blade.php
<!DOCTYPE html>
<html lang="km">
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>@yield('page_title')</title>
  <link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ asset('css/contract_print_v2.css') }}">    
</head>
<body>
  
  <h1 class="khmer-title text-center">ព្រះរាជាណាចក្រកម្ពុជា</h1>
  <h2 class="khmer-title text-center">ជាតិ សាសនា ព្រះមហាក្សត្រ</h2>
  <p class="text-center"><img src="{{ asset('img/kbach.png') }}"/></p>
  @yield('contract_type')
  <h3 class="khmer-title text-center">{{ $project->name }}</h3>
  <img src="{{ $project->logo_url }}" class="project-logo"/>
    
  <table class="table table-p-1 table-borderless">
    <tr>
      <td>លេខ៖ {{ $unit->code }}/{{ $unit_type->short_code }}-{{ $contract->formatted_id }}</td>
      <td class="text-right">ធ្វើនៅ ______________ ថ្ងៃទី _______________________</td>
    </tr>
  </table>

  <p><span class="khmer-title">ភាគី “អ្នកលក់”</span> ដែលមានអត្តសញ្ញាណដូចរៀបរាប់ក្នុងតារាងខាងក្រោម</p>

  <table class="table table-p-1 table-contract-bordered">
    <tr>
      <td width="180px" class="text-bold">នាមករណ៍</td>
      <td width="30px" class="text-center">៖</td>
      <td>ក្រុមហ៊ុន <span class="text-bold">{{ $project->company->name_km }}</span> <span class="english text-bold">({{ $project->company->name_en  }})</span></td>
    </tr>
    <tr>
      <td class="text-bold">លេខបញ្ជីពាណិជ្ជកម្ម</td>
      <td class="text-center">៖</td>
      <td>{{ $company->commercial_license_no_km }} ចុះថ្ងៃ​ទី {{ $company->commercial_license_issued_day_km }} ខែ {{ $company->commercial_license_issued_month_km }} ឆ្នាំ {{ $company->commercial_license_issued_year_km }}</td>
    </tr>
    <tr>
      <td class="text-bold">ទីស្នាក់ការចុះបញ្ជី</td>
      <td class="text-center">៖</td>
      <td>{{ $company->address_line1.' '.$company->address_line2 }}</td>
    </tr>
    <tr>
      <td class="text-bold">ឈ្មោះគម្រោង</td>
      <td class="text-center">៖</td>
      <td><span class="text-bold">{{ $project->name }}</span> <span class="english text-bold">({{ $project->name_en }})</span> @yield('project_suffix')</td>
    </tr>
    <tr>
      <td class="text-bold">តំណាងស្របច្បាប់ដោយ</td>
      <td class="text-center">៖</td>
      <td>ឈ្មោះ <span class="text-bold">{{  $sale_representative->name }}</span> ភេទ <span class="text-bold">{{ $sale_representative->gender_km }}</span> កើត​ថ្ងៃ​ទី {{ $sale_representative->birth_date_day_km }} ខែ {{ $sale_representative->birth_date_month_km }} ឆ្នាំ {{ $sale_representative->birth_date_year_km }} សញ្ជាតិខ្មែរ កាន់​អត្ត​សញ្ញាណ​ប័ណ្ណ​លេខ​ <span class="text-bold">{{ $sale_representative->national_id_km }}</span> ចុះ​ថ្ងៃ​ទី {{ $sale_representative->national_id_issued_day_km }} ខែ {{ $sale_representative->national_id_issued_month_km }} ឆ្នាំ {{ $sale_representative->national_id_issued_year_km }}</td>
    </tr>
    <tr>
      <td class="text-bold">លេខទូរស័ព្ទទំនាក់ទំនង</td>
      <td class="text-center">៖</td>
      <td>{{ $project->saleRepresentative->contact_number_km }}</td>
    </tr>
  </table>

  <p><span class="khmer-title">ភាគី “អ្នកទិញ”</span> ដែលមានអត្តសញ្ញាណដូចរៀបរាប់ក្នុងតារាងខាងក្រោម</p>
  <table class="table table-p-1 table-contract-bordered">
    <tr>
      <td width="180px" class="text-bold">១. នាម ឬនាមករណ៍</td>
      <td width="30px" class="text-center">៖</td>
      <td colspan="3"><span class="text-bold">{{ isset($is_template) ? '_______________' : $customer1['name'] }}</span></td>
    </tr>
    <tr>
      <td class="text-bold">ថ្ងៃខែឆ្នាំកំណើត</td>
      <td class="text-center">៖</td>    
      <td>ថ្ងៃទី {{ isset($is_template) ? '_____' : $customer1['birth_day'] }} ខែ {{ isset($is_template) ? '_____' : $customer1['birth_month'] }} ឆ្នាំ {{ isset($is_template) ? '_____' : $customer1['birth_year'] }}</td>
      <td width="100px">ភេទ៖ {{ isset($is_template) ? '_____' : $customer1['gender'] == 1 ? 'ប្រុស'  : 'ស្រី' }}</td>
      <td width="200px">សញ្ជាតិ៖ {{ isset($is_template) ? '_____' : $customer1['nationality'] }}</td>
    </tr>
    <tr>
      <td class="text-bold">កាន់អត្តសញ្ញាណប័ណ្ណលេខ ឬលិខិតឆ្លងដែនលេខ</td>
      <td class="text-center">៖</td>
      <td>{{ isset($is_template) ? '_________' : $customer1['nid_number'] }}</td>
      <td width="300px" colspan="2">ចុះថ្ងៃទី {{ isset($is_template) ? '_____' : $customer1['nid_issued_day'] }} ខែ {{ isset($is_template) ? '_____' : $customer1['nid_issued_month'] }} ឆ្នាំ {{ isset($is_template) ? '_____' : $customer1['nid_issued_year'] }}</td>
    </tr>
    @if( isset( $is_template ) ) 
    <tr>
      <td width="180px" class="text-bold">២. នាម ឬនាមករណ៍</td>
      <td width="30px" class="text-center">៖</td>
      <td colspan="3"><span class="text-bold">_______________</span></td>
    </tr>
    <tr>
      <td class="text-bold">ថ្ងៃខែឆ្នាំកំណើត</td>
      <td class="text-center">៖</td>
      <td>ថ្ងៃទី _____ ខែ _____ ឆ្នាំ _____</td>
      <td width="150px">ភេទ៖ _____</td>
      <td width="150px">សញ្ជាតិ៖ _____</td>
    </tr>
    <tr>
      <td class="text-bold">កាន់អត្តសញ្ញាណប័ណ្ណលេខ ឬលិខិតឆ្លងដែនលេខ</td>
      <td class="text-center">៖</td>
      <td>_________</td>
      <td width="300px" colspan="2">
      ចុះថ្ងៃទី _____ ខែ _____ ឆ្នាំ _____    
      </td>
    </tr>
    @else
      @if( $customer2['name'] != '' )
      <tr>
        <td width="180px" class="text-bold">២. នាម ឬនាមករណ៍</td>
        <td width="30px" class="text-center">៖</td>
        <td colspan="3"><span class="text-bold">{{ $customer2['name'] }}</span></td>
      </tr>
      <tr>
        <td class="text-bold">ថ្ងៃខែឆ្នាំកំណើត</td>
        <td class="text-center">៖</td>
        <td>ថ្ងៃទី {{ $customer2['birth_day'] }} ខែ {{ $customer2['birth_month'] }} ឆ្នាំ {{ $customer2['birth_year'] }}</td>
        <td width="150px">ភេទ៖ {{ $customer2['gender'] == 1 ? 'ប្រុស' : 'ស្រី' }}</td>
        <td width="150px">សញ្ជាតិ៖ {{ $customer2['nationality'] }}</td>
      </tr>
      <tr>
        <td class="text-bold">កាន់អត្តសញ្ញាណប័ណ្ណលេខ ឬលិខិតឆ្លងដែនលេខ</td>
        <td class="text-center">៖</td>
        <td>{{ $customer2['nid_number'] }}</td>
        <td width="300px" colspan="2">
        ចុះថ្ងៃទី {{ $customer2['nid_issued_day'] }} ខែ {{ $customer2['nid_issued_month'] }} ឆ្នាំ {{ $customer2['nid_issued_year'] }}    
        </td>
      </tr>
      @else
      <tr>
        <td width="180px" class="text-bold">២. នាម ឬនាមករណ៍</td>
        <td width="30px" class="text-center">៖</td>
        <td colspan="3"><span class="text-bold"></span></td>
      </tr>
      <tr>
        <td class="text-bold">ថ្ងៃខែឆ្នាំកំណើត</td>
        <td class="text-center">៖</td>
        <td></td>
        <td width="150px"></td>
        <td width="150px"></td>
      </tr>
      <tr>
        <td class="text-bold">កាន់អត្តសញ្ញាណប័ណ្ណលេខ ឬលិខិតឆ្លងដែនលេខ</td>
        <td class="text-center">៖</td>
        <td></td>
        <td width="300px" colspan="2">        
        </td>
      </tr>
      @endif
    @endif
    
    <tr>
      <td width="180px" class="text-bold">អាសយដ្ឋាន</td>
      <td width="30px" class="text-center">៖</td>
      <td colspan="3">{{ isset($is_template) ? '______________________________' : $contract->customer_address_line1.' '.$contract->customer_address_line2 }}</td>
    </tr>
    <tr>
      <td width="180px" class="text-bold">លេខទូរស័ព្ទទំនាក់ទំនង</td>
      <td width="30px" class="text-center">៖</td>
      <td colspan="3"><span class="text-bold">{{ isset($is_template) ? '______________________________' : $contract->customer_phone_number_km.($contract->customer_phone_number2_km ? ' / '.$contract->customer_phone_number2_km : '' ) }}</span></td>
    </tr>
  </table>
  <p>ភាគីទាំងពីរ ហៅដោយឡែកថា ភាគី <span class="text-bold">“អ្នកលក់”</span> ឬ ភាគី <span class="text-bold">“អ្នកទិញ”</span> ហើយហៅជារួមថា <span class="text-bold">“គូភាគី”</span> ដោយផ្អែកលើគោលការស្ម័គ្រចិត្ត និងស្មើភាព ភាគី <span class="text-bold">“អ្នកលក់”</span> និង ភាគី <span class="text-bold">“អ្នកទិញ”</span> បានព្រមព្រៀងគ្នាក្នុងការលក់ទិញនូវអចលនវត្ថុ ដែលមានអត្តសញ្ញាណ តម្លៃ និងខ្លឹមសារដូចខាងក្រោម៖</p>
  <div style="page-break-after: always;"></div>

  @yield('praka')

  <table class="table table-p-1 table-contract-bordered">    
  
  @if( isset($customer2['name']) ) 
    <tr>
      <td class="text-center"><span class="khmer-title">ភាគី “អ្នកលក់”</span></td>
      <td width="30px"></td>
      <td class="text-center"><span class="khmer-title">សាក្សី</span></td>
      <td width="30px"></td>
      <td class="text-center" colspan="3"><span class="khmer-title">ភាគី “អ្នកទិញ”</span></td>
    </tr>
    <tr>
      <td class="text-center text-bold" height="120px" width="25%" style="vertical-align:bottom">{{ $sale_representative->name }}</td>
      <td width="30px"></td>
      <td class="text-center" width="25%"></td>
      <td width="30px"></td>
      <td width="25%" class="text-center text-bold"  style="vertical-align:bottom">{{ isset($is_template) ? '____________' : $customer1['name'] }}</td>
      <td width="30px"></td>
      <td width="25%" class="text-center text-bold" style="vertical-align:bottom">{{ isset($is_template) ? '____________' : $customer2['name'] }}</td>
    </tr>
  @else
    <tr>
      <td class="text-center"><span class="khmer-title">ភាគី “អ្នកលក់”</span></td>
      <td width="30px"></td>
      <td class="text-center"><span class="khmer-title">សាក្សី</span></td>
      <td width="30px"></td>
      <td class="text-center"><span class="khmer-title">ភាគី “អ្នកទិញ”</span></td>
    </tr>
    <tr>
      <td class="text-center text-bold" height="120px" width="33%" style="vertical-align:bottom">{{ $sale_representative->name }}</td>
      <td width="30px"></td>
      <td class="text-center" width="33%"></td>
      <td width="30px"></td>
      <td class="text-center text-bold" width="33%" style="vertical-align:bottom">{{ isset($is_template) ? '____________' : $customer1['name'] }}</td>
    </tr>
  @endif
  </table>
  <div style="page-break-after: always;"></div>
    

  @include('admin.contract.template.v2.km.payment_schedule')
  
  @yield('first')
  @yield('second')
  @yield('third')
  @yield('forth')
</body>
</html>