routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::redirect('/', '/login', 301);
// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', "Auth\LoginController@authenticate");
Route::post('/logout', "Auth\LoginController@logout")->middleware(['auth'])->name('logout');
Route::get("/change-password", "Auth\ChangePasswordController@showChangePasswordForm")->middleware(['auth'])->name('password.change');
Route::post("/change-password", "Auth\ChangePasswordController@changePassword")->middleware(['auth']);

// Contract Template Route
Route::get("/contract_template/{template_path}/preview", "ContractTemplatePreviewController@preview")
     ->name('admin.contract_templates.preview');
Route::get("/ios/install", "AppDownloadController@showIOSDownloadView")->name("app_download.ios");
Route::get("/ios/install/dev", "AppDownloadController@showIOSDevDownloadView")->name("app_download.ios_dev");
Route::get('/contract/templates', 'ContractTemplatePreviewController@showTemplate')
    	 ->name('contracts.template')
    	 ->middleware(['role:contract_controller']);
// End Contract Template Route

Route::namespace("Admin")->prefix('admin')->name("admin.")->middleware(['auth'])->group( function () {
	Route::get('/users', "UserController@index")->name('user.all')
		 ->middleware('permission:view-user');
	Route::get('/users/new', "UserController@create")->name('user.new')
	     ->middleware('permission:create-user');
	Route::get('/users/get_agents', "UserController@getAgents")->name('user.role.agent');
	Route::get('/users/{id}', 'UserController@show')->name('user.show');
	Route::get('/users/{id}/tokens', "UserTokenController@show")->name('user.token.show')
		 ->middleware('permission:view-user');
	Route::get('/users/{id}/edit', "UserController@edit")->name('user.edit')
		 ->middleware('permission:update-user');
	Route::get('/users/{id}/password/reset', "UserController@showPasswordForm")->name('user.password.show')
		 ->middleware('permission:update-user');
	Route::post('/users/{id}/password/reset', "UserController@resetPassword")->name('user.password.reset')
		 ->middleware('permission:update-user');
	Route::post('/users', "UserController@store")->name('user.create')
		 ->middleware('permission:create-user');
	Route::put('/users/{id}', "UserController@update")->name('user.update')
		 ->middleware('permission:update-user');

	Route::delete('/tokens/{id}', "UserTokenController@destroy")->name('user.token.delete')
		 ->middleware('permission:update-user');

	Route::middleware('role:administrator')->group( function () {
		Route::get('/roles', "RoleController@index")->name('role.all');
		Route::get('/roles/new', "RoleController@create")->name('role.new');
		Route::get('/roles/{id}/edit', "RoleController@edit")->name('role.edit');
		Route::get('/roles/{id}/remove', "RoleController@remove")->name('role.remove');	
		Route::post('/roles', "RoleController@store")->name('role.create');
		Route::put('/roles/{id}', "RoleController@update")->name('role.update');
		Route::delete('/roles/{id}', "RoleController@delete")->name('role.delete');
	});

	Route::get('/contract_requests', "ContractRequestController@index")
		 ->name('contract_request.all');	
	Route::get('/contract_requests/{id}', "ContractRequestController@show")
		 ->name('contract_request.show');
	Route::put('/contract_requests/{id}', "ContractRequestController@update")
	     ->name('contract_request.update');   
	Route::get('/contract_requests/{id}/view_payment_sample', 'ContractRequestController@showMortgage')
		 ->name('contract_request.view_payment_sample');

	// Unit Contract Request
	Route::get("/unit_contract_requests", "UnitContractRequestController@index")
	     ->name('unit_contract_requests.index');	
	Route::get("/unit_contract_requests/{id}", "UnitContractRequestController@show")
	     ->name('unit_contract_requests.show');
	Route::get("/unit_contract_requests/{id}/createContract", "UnitContractRequestController@showCreateContractForm")
	     ->name('unit_contract_requests.create_contract')
	      ->middleware('permission:create-contract');;
	Route::get('/unit_contract_requests/{id}/print', "UnitContractRequestController@printRequest")
		 ->name('unit_contract_requests.print');

	// Unit Deposit Request
	Route::get("/unit_deposit_requests", "UnitDepositRequestController@index")
	     ->name('unit_deposit_requests.index')
	     ->middleware('permission:view-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}", "UnitDepositRequestController@show")
	     ->name('unit_deposit_requests.show')
	     ->middleware('permission:view-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}/updateReceivingAmount", "UnitDepositRequestController@showUpdateReceivingAmountForm")
	     ->name('unit_deposit_requests.update.receving_amount')
	     ->middleware('permission:view-unit-deposit-request');
	Route::post("/unit_deposit_requests/{id}/updateReceivingAmount", "UnitDepositRequestController@UpdateReceivingAmount")
		 ->middleware('permission:update-unit-deposit-request');
	Route::post('/unit_deposit_requests/{id}/cancel', 'UnitDepositRequestController@cancel')
		 ->name('unit_deposit_requests.cancel')
		 ->middleware('permission:cancel-unit-deposit-request');
	Route::post('/unit_deposit_requests/{id}/void', 'UnitDepositRequestController@void')
		 ->name('unit_deposit_requests.void')
		 ->middleware('permission:void-unit-deposit-request');
	Route::get("/unit_deposit_requests/{id}/getPayment", "UnitDepositRequestController@getPayment")->name('unit_deposit_requests.payment');

	// Unit Hold Request
	Route::get('/unit_hold_requests', 'UnitHoldRequestController@index')
		 ->name('unit_hold_requests.index')
	     ->middleware('permission:view-unit-hold-request');
	Route::get("/unit_hold_requests/{id}", "UnitHoldRequestController@show")
	     ->name('unit_hold_requests.show')
	     ->middleware('permission:view-unit-hold-request');

	// Contract Route
	Route::get('/contracts', "ContractController@index")
		 ->name('contracts.index')
		 ->middleware('permission:view-contract');

	Route::get('/contracts/export', 'ContractController@export')
		 ->name('contracts.export')
		 ->middleware('permission:view-contract');

	Route::get('/contracts/create', "CreateContractController@showCreateForm")
		 ->name('contracts.create')
		 ->middleware('permission:create-contract');

	Route::get('/contracts/{id}/edit', "EditContractController@showEditForm")
		 ->name('contracts.edit')
		 ->middleware('permission:update-contract');

    Route::get('/contracts/{id}/print', 'ContractPdfController@getContractPdfFile')
		 ->name('contracts.print')
		 ->middleware('permission:view-contract');

    Route::get('/contracts/{id}/upload', 'UploadContractController@showContractUploadForm')
		 ->name('contracts.upload')
		 ->middleware('permission:update-contract');
    Route::post('/contracts/{id}/upload', 'UploadContractController@uploadContractPDF')
    	 ->middleware('permission:update-contract');;

	Route::post('/contracts/create', "CreateContractController@store")
	     ->middleware('permission:create-contract');

	Route::post('/contracts/{id}/cancel', "CancelContractController@processCancellationRequest")
	     ->middleware('permission:cancel-contract');
	Route::post('/contracts/{id}/void', "VoidContractController@processVoidRequest")
	     ->middleware('permission:void-contract');

	Route::put('/contracts/{id}', "EditContractController@update")
		 ->name('contracts.update')
		 ->middleware('permission:update-contract');
	// End Contract Route

	// Contract Attachment Route
    Route::delete('/contract_attachments/{id}', "ContractAttachmentController@delete")
         ->name('contract_attachments.destroy');
	// Contract Attachment Route

	// Loan Route
	Route::post('/loan/amortization-schedule', "LoanController@getAmortizationSchedule")
		 ->name('loan.amortization-schedule');
    Route::get('/loan/payment_date', "LoanController@paymentDate");
	// End Loan

	// Banner
    Route::resource('banners', 'BannerController');
	// End Banner

	// Bank
    Route::resource('banks', 'BankController');
	// End Bank

	// Banner
    Route::resource('categories', 'CategoryController');   
	// End Banner

   	// Banner
    Route::resource('posts', 'PostController');    
	// End Banner

	Route::resource('projects', 'ProjectController');
	Route::get('projects/{id}/delete', "ProjectController@showDeleteForm")->name('projects.delete');
	Route::get('projects/{id}/restore', "ProjectController@showRestoreForm")->name('projects.restore');
	Route::post('projects/{id}/restore', "ProjectController@restore");
	Route::delete('projects/{id}/media', 'ProjectController@deleteMedia')->middleware('permission:update-project');

	Route::resource('companies', 'CompanyController');
	Route::get('companies/{id}/delete', 'CompanyController@delete')->name('companies.delete');

	Route::resource('payment_options', 'PaymentOptionController');
	Route::get('payment_options/{id}/delete', "PaymentOptionController@showDeleteForm")->name('payment_options.delete');
	Route::get('payment_options/{id}/restore', "PaymentOptionController@showRestoreForm")->name('payment_options.restore');
	Route::post('payment_options/{id}/restore', "PaymentOptionController@restore");
	Route::get('payment_options/{id}', "PaymentOptionController@show");

	// Discount Promtion Route
	Route::resource('discount_promotions', 'DiscountPromotionController');
	Route::post('discount_promotions/{id}/discount_promotion_items', 'DiscountPromotionController@addItem');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Helpers\UserRole;
use App\Traits\UserActiveStatusNotification;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
	use UserActiveStatusNotification;

	protected $validationRules =  [
		'name' 				=> 'required|string|min:6|max:191', 
		'email' 			=> "nullable|email|unique:users,email",				        
		'phone_number'  	=> "required|regex:^0\d{8,9}^|unique:users,phone_number",
		'gender' 			=>  'in:Male,Female',
		'birthdate' 	    => 'date',
		'managed_by'        => "required|integer|min:0",
		'avatar'			=> 'image|dimensions:min_width=256,min_height=256,max_width=1028,max_height=1028',
		'identification_id' => 'exists:user_identifications,id'
	];

	public function index(Request $request)   
	{
		$roles = Role::get(['id','name']);
		$users = User::query();
		$users = $users->with(['roles']);

		if ( $request->query('term') ) {
			$term = $request->query('term');
			$users = $users->where('name' , 'LIKE', '%'.$term.'%');
			$users = $users->orWhere('email' , 'LIKE', '%'.$term.'%');
			$users = $users->orWhere('phone_number' , 'LIKE', '%'.$term.'%');
		}

		if ( $request->query("role") AND $request->query("role") != "" ) {
			$users = $users->role($request->query("role"));
		}

		if ( $request->query('verified') ) {
			$is_verified = strcasecmp($request->query('verified'), 'true') == 0 ? true : false;
			$users = $users->ofVerified($is_verified);
		}

		if ( $request->query('active') ) {
			$is_active = strcasecmp($request->query('active'), 'true') == 0 ? true : false;
			$users = $users->ofActive($is_active);
		}

		if ( auth()->user()->hasRole(UserRole::SALE_MANAGER) ) {
			$users = $users->role([UserRole::SALE_TEAM_LEADER, UserRole::AGENT]);
		}

		$users = $users->paginate(10);

		return view('admin.user.index', compact('users','roles'));
	}

	public function edit(Request $request, $id)
	{
		$user = User::with(['roles'])->findOrFail($id);
		$roles = Role::all();
		$users = User::all();	
		return view('admin.user.edit', compact('user','roles','users'));
		
	}

	public function create()
	{
		$roles = Role::all();
		$users = User::all();
		return view('admin.user.new',compact('roles', 'users'));
	}

	public function show(Request $request, $id) 
	{
		// It is used on Contract Page.
		if ($request->ajax()) {
			return $this->getUserAjaxResposne($id);
		}

		$user = User::query();		
		$auth_role = auth()->user()->roles()->first();
	
		switch ($auth_role->name) {
			case UserRole::ADMINISTRATOR:
				$user = User::findOrFail($id);				
				break;
			case UserRole::SALE_MANAGER:
				$user = User::role([UserRole::AGENT, UserRole::SALE_TEAM_LEADER])
						->where('id', $id)
						->firstOrFail();
				break;
			default:
				return abort(404);
				break;
		}

		return view('admin.user.single', compact('user'));
	}

	public function store(Request $request)
	{
		$validation_rule = $this->getValidationRules();
		$validation_rule['password'] = "required|string|min:6|confirmed";

		$validatedData = $request->validate($validation_rule);

		try {			
			$user = User::create([
				'name' => $request->name,
				'email' => $request->email,
				'phone_number' => $request->phone_number,
				'gender' => $request->gender,
				'need_change_password' => $request->need_change_password ? 1 : 0,
				'active' => $request->active ? 1 : 0,
				'verified' => $request->verified ? 1 : 0,
				'password' => bcrypt($request->password),
				'managed_by' => $request->managed_by
			]);

			$role = Role::findOrFail($request->role);

			$user->syncRoles($role);

			return redirect()->route('admin.user.edit', ['id' => $user->id])
						 	 ->with('status', "User has been created successfully.");
		} catch (\Exception $e) {
			return back()->withInput()->withErrors([ 'user' => $e->getMessage()]);
		}
	}

	public function update(Request $request, $id)
	{
		$user = User::findOrFail($id);
		$role = Role::findOrFail($request->role);
		$phone_number_changed = false;

		$validation_rule = $this->getValidationRules();
		$validation_rule['phone_number'] = "required|regex:/0[0-9]{8,9}/|between:9,10|unique:users,phone_number,".$user->id;
		$validation_rule['email'] = "nullable|email|unique:users,email,".$user->id;

		if ( strcmp( $request->phone_number, $user->phone_number ) != 0 ) {
			$phone_number_changed = true;
		}

		$validatedData = $request->validate($validation_rule);

		try {
			$user->fill($request->all());			
			$user->active = $request->active ? 1 : 0;
			$user->verified = $request->verified ? 1 : 0;

			if ( $user->isDirty('active') ) {			
				$this->sendUserActiveStatusNotification($user);
			}

			$user->save();
			if ( $phone_number_changed ) {
				$user->tokens()->delete();
			}
			if ( !$user->hasRole($role) ){
				$user->tokens()->delete();
				$user->syncRoles($role);
			}
		} catch (\Exception $e) {
			return back()->withInput()->withErrors(['user' => $e->getMessage()]);
		}
		return back()->with('status', 'User has been updated successfully');
	}

	public function showPasswordForm($id){
		$user = User::findOrFail($id);
		return view('admin.user.password_reset', compact('user'));
	}

	public function resetPassword(Request $request, $id)
	{
		$user = User::findOrFail($id);

		$validatedData = $request->validate([
	        'password' => 'required|string|min:6|confirmed'
	    ]);

	    try {
	    	$user->password = bcrypt($request->password);	    
	    	$user->need_change_password = $request->input('need_change_password') ? 1 : 0;
	    	$user->save();
	    	$user->tokens()->delete();
	    	
	    } catch (\Exception $e) {
	    	return back()->withErrors([ 'password' => $e->getMessage()]);
	    }

		return back()->with('status', "Password has been reset successfully.");
	}

	public function getValidationRules(){
		return $this->validationRules;
	}

	public function getAgents(Request $request) 
	{		
		$agents = User::role([UserRole::AGENT,UserRole::SALE_TEAM_LEADER])->with(['manager']);
		if ( $request->ajax() ) {
			if ( $request->query('term') ) {
	            $term = $request->query('term');
	            $agents = $agents->where('name' , 'LIKE', '%'.$term.'%');      
	        }		
			return response()->json( $agents->simplePaginate() );
		}
		return $agents->get();
	}

	private function getUserAjaxResposne($id) {
		return response()
            ->json(User::findOrFail($id));
	}
}

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">User : {{ $user->name }}</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form method="POST" action="{{ route('admin.user.update', ['id'=> $user->id]) }}" novalidate="novalidate" autocomplete="false">
                        @csrf
                        {{ method_field('PUT') }}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Name: <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" name="name" id="name" placeholder="User Fullname" value="{{ $user->name }}">
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <label for="email">Email: </label>
                                    <input type="email" class="form-control" 
                                           name="email" 
                                           id="email" 
                                           placeholder="Email Address : yourname@yourdomain.com"
                                           value="{{ $user->email }}">
                                </div>  
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="name">Phone Number: <span class="text-danger">*</span> <span class="text-muted">used for login</span></label>
                                    <input type="text" class="form-control" 
                                           name="phone_number" id="phone_number" 
                                           placeholder="0123456789"
                                           value="{{ $user->phone_number }}">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="gender">Gender: </label>
                                    <select class="form-control" name="gender" id="gender">
                                        <option value="0" {{ $user->gender ? "selected" : "" }}>N/A</option>
                                        <option value="Male" {{ $user->gender == "Male" ? "selected" : ""}}>Male</option>
                                        <option value="Female" {{ $user->gender == "Female" ? "selected" : ""}}>Female</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" name="verified" id="verified" {{ $user->verified ? 'checked' : '' }}>
                            <label class="form-check-label" for="verified">{{ __("Account does not need to be verified.") }}</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" name="active" id="active" {{ $user->active ? 'checked' : '' }}>                            
                            <label class="form-check-label" for="active">{{ __("Make account as active. (Inactive account will not be able to use the application.)") }}</label>
                        </div>

                        <div class="form-group">
                            <label for="managed_by">Managed By: </label>
                            <select class="form-control" name="managed_by" id="managed_by">
                                <option value="0">N/A</option>
                                @foreach( $users as $u )
                                <option value="{{$u->id}}" {{ ( $user->managed_by == $u->id ? "selected" : "" ) }}>{{ $u->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="role">Role: </label>
                            <select class="form-control" name="role" id="role">
                                @foreach( $roles as $role )
                                <option value="{{$role->id}}" {{ ( $user->hasRole($role) ? "selected" : "" ) }}>{{ str_replace('_',' ',title_case($role->name)) }}</option>
                                @endforeach
                            </select>
                        </div>
                        <p class="text-info">**Change the user's Phone Number will remove all login session in mobile app.</p>

                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                            <div class="col">
                                <a href="{{ route('admin.user.all') }}" class="btn btn-secondary float-right">Back to User List</a> 
                                <a href="{{ route('admin.user.password.show',['id'=>$user->id]) }}" class="btn btn-danger float-right mx-2">{{ __('Reset Password') }}</a>                                  
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <form method="GET" action="{{ route('admin.user.all') }}" name="user-search-from" novalidate="novalidate" autocomplete="false">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            User List : <a href="{{route('admin.user.new')}}" class="btn btn-primary btn-sm ">Create New User</a>
                        </div>
                        <div class="col-sm-12 col-md-auto" style="width:400px;">                           
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Name, email or phone number" aria-label="Name, email or phone number" aria-describedby="button-search" name="term" value="{{ Request::query('term') ? Request::query('term') : '' }}">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="submit" id="search-button">Search</button>
                                    <a class="btn btn-outline-secondary" data-toggle="collapse" href="#sub-header-collapse">{{ __("More Filter") }}</a>
                                </div>
                            </div>
                        </div>
                    </div>                    
                </div>
                <div class="card-sub-header card-bg-grey collapse {{ Request::query() ? 'show' : '' }}" id="sub-header-collapse">
                    <div class="sub-header-box-wrapper">
                        <div class="form-row">
                            <div class="input-group input-group-sm col-md-3">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="role_select">Role</label>
                                </div>
                                <select class="form-control" name="role" id="role_select">
                                    <option value="">Choose...</option>
                                    @foreach($roles as $role)
                                    <option value="{{ $role->id }}" {{ Request::query('role') == $role->id ? 'selected' : '' }}>{{ str_replace('_',' ', title_case($role->name)) }}</option>
                                    @endforeach                                    
                                </select>
                            </div>                          
                            <div class="input-group input-group-sm col-md-2">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="active">{{ __("Active?") }}</label>
                                </div>
                                <select class="form-control" name="active" id="active">
                                    <option value="">{{ __("All") }}</option>
                                    <option value="true" {{ Request::query('active') == 'true' ? 'selected' : '' }}>{{ __("Yes") }}</option>
                                    <option value="false" {{ Request::query('active') == 'false' ? 'selected' : '' }}>{{ __("No") }}</option>
                                </select>
                            </div>
                            <div class="input-group input-group-sm col-md-2">
                                <div class="input-group-prepend">
                                    <label class="input-group-text" for="verified">{{ __("Verified?") }}</label>
                                </div>
                                <select class="form-control" name="verified" id="verified">
                                    <option value="">{{ __("All") }}</option>
                                    <option value="true" {{ Request::query('verified') == 'true' ? 'selected' : '' }}>{{ __("Yes") }}</option>
                                    <option value="false" {{ Request::query('verified') == 'false' ? 'selected' : '' }}>{{ __("No") }}</option>
                                </select>
                            </div>
                            <button class="btn btn-sm btn-primary" type="submit" id="fileter-button">Show</button>    
                            <a href="{{ route('admin.user.all') }}" class="btn btn-secondary btn-sm ml-md-2">Clear Filter</a>
                        </div>
                    </div>
                </div>
                <div class="card-body p-0">
                    <table class="table table-hover table-action mb-0">
                        <thead>
                            <tr>
                                <th scope="col" width="60px"></th>
                                <th scope="col">Name</th>
                                <th scope="col" width="150px">{{ __("Phone Number") }}</th>
                                <th scope="col" width="100px">{{ __("Gender") }}</th>
                                <th scope="col" width="70px">{{ __("Active") }}</th>
                                <th scope="col" width="70px">{{ __("Verified") }}</th>                                
                                <th scope="col" width="150px">{{ __("Member Since") }}</th>
                                <th scope="col" width="30px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td scope="row">
                                    <img src="{{ $user->avatar_url }}" class="user-avatar-50" alt="{{ $user->name }}">
                                </td>
                                <td class="action-td">
                                    <a href="{{ route('admin.user.show',['id'=>$user->id]) }}" class="title" >{{ $user->name }}</a>
                                    <span class="d-block text-muted">
                                        @if( isset($user->roles[0]) )
                                        {{ str_replace('_',' ', title_case($user->getRoleNames()[0]) )}}
                                        @else
                                        N/A
                                        @endif
                                    </span>
                                </td>
                                <td><b>{{ $user->phone_number }}</b></td>
                                <td>{{ $user->gender }}</td>
                                <td>{!! $user->getActiveHtml() !!}</td>
                                <td>{!! $user->getVerifiedHtml() !!}</td>
                                <td>{{ $user->created_at->diffForHumans() }}</td>
                                <td>
                                    <div class="dropdown">
                                        <a href="#" class="text-primary" data-toggle="dropdown" data-display="static" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-lg fa-ellipsis-v"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg-left" aria-labelledby="zdropdownMenuButton">
                                            <a href="{{ route('admin.user.show', [ 'id' => $user->id ] ) }}" class="dropdown-item">
                                                {{__("View")}}
                                            </a>
                                            <a href="{{ route('admin.user.edit', [ 'id' => $user->id ] ) }}" class="dropdown-item">
                                                {{__("Edit")}}
                                            </a>
                                            <a href="{{ route('admin.user.password.show', ['id' => $user->id]) }}" class="dropdown-item"> {{ __('Reset Password') }}</a>
                                            <a href="{{ route('admin.user.token.show', ['id' => $user->id]) }}" class="dropdown-item">{{ __('Login Devices') }}</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            </form>
            {{ $users->appends(request()->except(['page','_token'])) }}
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
    
</script>
@endpush